[package]
name = "assets"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
itertools = "0.10.0"

[dev-dependencies]
near-sdk-sim = "3.1.0"
